sudo: required
dist: trusty
language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 6
  - 8
  - 9
  - 10
before_script:
  - npm run build
script:
  - npm run test:ci
after_success:
  - npm run codecov
notifications:
  email: false
